# Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/
from directories import get_run_dir
from installation import ClassicInstallerSupplier
from mediaserver_api import Forbidden
from mediaserver_scenarios.provisioned_mediaservers import FTMachinePool
from tests.infra import assert_raises
from tests.single_server.permissions.common import get_api_for_actor


def _test_cannot_add(distrib_url, one_vm_type, api_version, actor, exit_stack):
    installer_supplier = ClassicInstallerSupplier(distrib_url)
    pool = FTMachinePool(installer_supplier, get_run_dir(), api_version)
    one_mediaserver = exit_stack.enter_context(pool.one_mediaserver(one_vm_type))
    one_mediaserver.mediaserver().start()
    one_mediaserver.mediaserver().api.setup_local_system()
    mediaserver = one_mediaserver.mediaserver()
    mediaserver_api_for_actor = get_api_for_actor(mediaserver.api, actor)
    with assert_raises(Forbidden):
        # The API for add_license method doesn't check if license key and block is valid
        # (generated by license server). Fake license key is enough here to check user permissions.
        fake_license_key = '1111-1111-1111-1111'
        mediaserver_api_for_actor.add_license(fake_license_key, license_block='Test License')
